# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # the python version currently just matches a version used to
    # succesfully construct the documents locally
    python: "3.7"


python:
   install:
   - requirements: doc/source/requirements.txt

# Build PDF & ePub
formats:
  - epub
  - pdf
